version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongo
    volumes:
      - /home/amir/Documents/Scripts/JS/task-manager/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  node:
    image: public.ecr.aws/c1h2f5u7/tskmgr:latest
    container_name: node
    environment:
      MONGO_URI: "mongodb://mongo:27017"
    ports:
      - 5000:5000
    restart: always
    links:
      - mongodb
